
/*
PATH HAS BEEN AUTO-GENERATED BY THE PYTHON PARSER. DO NOT TOUCH OR YOU WILL HAVE BAD LUCK FOR 100 YEARS.
*/

public class stuff {
	public double[] generated_Velocities = {
		1,
		3,
		5.5,
		7.5
	};
	public double[] generated_Rotations = {
		2,
		4,
		6.5,
		8.5
	};
}

