import sys

fileName = sys.argv[1]
outputFile = sys.argv[2]
i = 0
velocities = []
rotations = []
with open(fileName) as f, open(outputFile, "w") as out:
	for line in f.readlines():
		for entry in line.strip().split(" "):
			if i == 0:
				velocities.append(entry)
			if i == 1:
				rotations.append(entry)

			out.write(entry + " ")
			i+=1
			if i == 6:
				i = 0
				out.write("\n")
		

velocityArray = ",\n\t\t".join(velocities)
rotationsArray = ",\n\t\t".join(rotations)

content = """
/*
PATH HAS BEEN AUTO-GENERATED BY THE PYTHON PARSER. DO NOT TOUCH OR YOU WILL HAVE BAD LUCK FOR 100 YEARS.
*/
package frc.robot;

public class stuff {
	public double[] generated_Velocities = {
		%s
	};
	public double[] generated_Rotations = {
		%s
	};
}

""" % (velocityArray, rotationsArray)

with open(fileName + ".java", "w") as f:
	f.write(content)
