
/*
PATH HAS BEEN AUTO-GENERATED BY THE PYTHON PARSER. DO NOT TOUCH OR YOU WILL HAVE BAD LUCK FOR 100 YEARS.
*/
package frc.robot;

public class Test {
	public double[] generated_Velocities = {
		0.0
	};
	public double[] generated_Rotations = {
		0.0
	};
	public double[] generated_leftEncoderPositions = {
		5.4
	};
	public double[] generated_rightEncoderPositions = {
		-5.3
	};

}

